[package]
name = "norts"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["ai", "tictactoe",]
publish = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

